// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -O1 -triple h2blb -emit-llvm -o - %s | FileCheck %s

// REQUIRES: h2blb-registered-target

// CHECK-LABEL: define dso_local i32 @widening_multiply_by_3(
// CHECK-SAME: i16 noundef signext [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 asm "wsmul $0, $1, #3", "=r,r"(i16 [[A]]) #[[ATTR1:[0-9]+]], !srcloc [[META6:![0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int widening_multiply_by_3(short a) {
  int Result;
  asm("wsmul %0, %1, #3" : "=r"(Result) : "r"(a));
  return Result;
}
//.
// CHECK: [[META6]] = !{i64 619}
//.
