#!/usr/bin/env bash
cmake llvm -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=g++ \
  -DLLVM_ENABLE_PROJECTS="clang;mlir" \
  -DLLVM_TARGETS_TO_BUILD="Native;RISCV;NVPTX" \
  -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=Toy \
  -DLLVM_CCACHE_BUILD=true \
  -DBUILD_SHARED_LIBS=true \
  -DLLVM_OPTIMIZED_TABLEGEN=true \
  -DLLVM_BUILD_TESTS=true
