; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -o - %s | FileCheck %s

target triple="h2blb"

define i32 @widening_smul(i16 %a, i16 %b) {
; CHECK-LABEL: define i32 @widening_smul(
; CHECK-SAME: i16 [[A:%.*]], i16 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.h2blb.widening.smul(i16 [[A]], i16 [[B]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %res = call i32 @llvm.h2blb.widening.smul(i16 %a, i16 %b)
  ret i32 %res
}

define i32 @widening_umul(i16 %a, i16 %b) {
; CHECK-LABEL: define i32 @widening_umul(
; CHECK-SAME: i16 [[A:%.*]], i16 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.h2blb.widening.umul(i16 [[A]], i16 [[B]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %res = call i32 @llvm.h2blb.widening.umul(i16 %a, i16 %b)
  ret i32 %res
}
